### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by nopara73** [hudon/refraction-hs#74]
Hi @hudon, I'm watching this repo and I noticed, you committed today since a long time. Are you planning to restart the work on this again? Best! nopara73

**Comment by nopara73** [comment]
Also you may be interested following this issue: https://github.com/nopara73/ZeroLink/issues/67

**Comment by hudon** [comment]
Yes, work has restarted since yesterday. The code basically works as a demo end-to-end.
The goal is to have at least 1 reference implementation of Xim out there
